// Playing with a 2D array - exploring a MAZE generated by copilot.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>

#include <vector>


using std::cout;
using std::vector;

const int ROWS = 10; //global vars 
const int COLS = 10;

void generateMaze(char maze[ROWS][COLS]) 
{
    // Initialize the maze with walls
    for (int i = 0; i < ROWS; ++i) 
    {
        for (int j = 0; j < COLS; ++j) 
        {
            maze[i][j] = '#';
        }
    }

    // Create a simple path
    for (int i = 1; i < ROWS - 1; ++i)
    {
        maze[i][1] = ' ';
    }
    for (int j = 1; j < COLS - 1; ++j) 
    {
        maze[ROWS - 2][j] = ' ';
    }

    // Add entrance and exit
    maze[1][1] = 'S'; // Start
    maze[ROWS - 2][COLS - 2] = 'E'; // End
}


void printMaze(const char maze[ROWS][COLS]) 
{
    //maze[1][1] = 'z' //error!
    for (int i = 0; i < ROWS; ++i) 
    {
        for (int j = 0; j < COLS; ++j) 
        {
            cout << maze[i][j] << ' ';
        }
        cout << '\n';
    }
}

//void traverseMaze()

int main()
{
    //ROWS
    //int a; //a "local" variable 
    //std::cout << "Hello World!\n";
    char maze[ROWS][COLS]; 

    generateMaze(maze); 
    printMaze(maze); 

    int currentRow = 2; 
    int currentCol = 1; 

    char currentChar = maze[currentRow][currentCol]; 

    char positionMarker = '*'; 

    maze[currentRow][currentCol] = positionMarker; 

    while (currentChar != 'E')
    {
        system("pause"); 
        system("CLS");

        printMaze(maze); 

        cout << "Enter up (w), down (s), left (a), right (d) ...\n";
        char choice;
        std::cin >> choice; 

        switch (choice)
        {
        case 'w':
            cout << "The character above is a: " << maze[currentRow - 1][currentCol] << "\n";
            //if(maze[currentRow - 1][currentCol])
            break; 

        }
        

        //currentChar = ...
    }
}
